### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by staeff** [comment]
Sorry, I didn't come around to proceed with this branch and thanks at @petschki for moving the ball forward. I had two things in mind to improve the package. That made the task a bigger and stopped me in the end from tackling it.

* I didn't want to update the requests to googles captcha service to use the `requests` - library instead of `urllib` that now needs to be wrapped with six. Afaik - `requests` is used quite a bit in several places in plone and add-ons, so adding this dependency should be okay.

* I wanted add tests. This has been started by @petschki. Should there be tests for the functionality of the form? Which seems tricky to, since the functionality is mostly getting a responce from googles recaptcha service. But there are some settings as well in the form. Are they worth to be tested?

Generally I'd say this PR is a good enough version to merge. Cherries can be put on top later.

**Review by staeff — APPROVED** [review]
Left my comment as regular comment.

**Comment by staeff** [comment]
@petschki - are you done with your work on the repo? I might have some changes and don't want to step on your toes. I'd leave a comment, when I don't have things to add. Then we can do the merge and the release.

By that way wouldn't you like to mention yourself in the Changelog?

**Comment by petschki** [comment]
@staeff now I'm done 😉

**Comment by petschki** [comment]
As you said. I'd also merge and release the first Py3 compatible version as soon as possible and do some cosmetics later on ...

**Review by jensens — APPROVED** [review]

**Comment by staeff** [comment]
Hi @jensens - would you release this?

**Pull request merged**
