### PR TITLE
recaptcha API v2

### PR DESCRIPTION
**Pull request by mamico**
support for new Google reCaptcha API
http://googleonlinesecurity.blogspot.it/2014/12/are-you-robot-introducing-no-captcha.html

### CODE REVIEW

**Comment by mamico** [comment]
@davisagli @tisto any feedback about this proposal?

**Comment by tisto** [comment]
Looks good. Will try to find time to look into it this week...

**Comment by davidjb** [comment]
Tested with Plone 4.3.4 and no problems.  V1 API keys are no longer being issued and as such, reCAPTCHA can only be used with the V2 API from now on.

My only suggestion is that this changes makes it incompatible with any sites that are currently using the V1 API (and have V1 keys stored).  Upgrading to a new version of this widget will see sites break, so a suitable disclaimer should be added to the readme/change log to alert people.

Google's error for using V1 keys with the V2 API isn't user friendly:  "An internal error occurred: [error code]" is the text that appears on the page instead of the CAPTCHA.  The error code structure made it look like a Plone error, which had me chasing my tail.

Otherwise, can this be merged / released?

**Comment by mamico** [comment]
@davidjb 

> My only suggestion is that this changes makes it incompatible with any sites that are currently using the V1 API (and have V1 keys stored). Upgrading to a new version of this widget will see sites break, so a suitable disclaimer should be added to the readme/change log to alert people.

I write something about here: https://github.com/plone/plone.formwidget.recaptcha/pull/1/files#diff-26fd799ea07494916e9da9b91b2aac64R39

Do you think it's pretty well explained (my english could be really bad) or need some improvements?

**Comment by djowett** [comment]
As someone who's better at English than I am at any other language ;-), can I suggest:

plone.formwidget.recaptcha 2.\* uses V2 of the reCaptcha API. Users upgrading from plone.formwidget.recaptcha 1.\* will therefore need to generate new keys as global Keys are not supported in the V2 API.

**Comment by davidjb** [comment]
@djowett looks good to me.  Anything else preventing this from being merged & released?

**Pull request merged**
